#!/bin/bash
# still todo
# for now: gsyn_up after every change / gsyn_down when switching device

set -u
set -e

echo "installing/updating DotFiles..."
DotFilesDir=~/DotFiles

#* add or replace in .bashrc source of mybashrc
echo '* look in file ~/.bashrc for line containing .mybashrc_all, and poss. replace or add line to source it' 
grep_result=$(cat ~/.bashrc | grep '.mybashrc_all' || true) # '|| true is necessary to prevent exiting under set -e, since grep has exit code 0, when it finds nothing (i could have taken 'if cat ... | grep ...' directly in if statement, but i prefer to have maintainability by having the "grep_result" variable at my disposal) 
echo "    grep_result = $grep_result"
echo

if [ -z "$grep_result" ]
then #empty
    echo '    no line found in ~/.bashrc with "... mybashrc_all"' 
    echo "source "$DotFilesDir"/.mybashrc_all" >> ~/.bashrc
    # echo "empty --> append source-command"
    echo "    --> I have put source-command into the ~/.bashrc: source "$DotFilesDir"/.mybashrc_all" 
else
    echo '    line found in ~/.bashrc with "... mybashrc_all"' 
    echo ' --> replace the line with: source '$DotFilesDir'/\.mybashrc_all'
    sed -i 's%^.*mybashrc_all.*$%source '$DotFilesDir'/\.mybashrc_all%g' ~/.bashrc
    echo "    put source-command into the ~/.bashrc: source "$DotFilesDir"/.mybashrc_all" 
fi


#* symlinks (delete existing dotfiles)
echo '* symlinks (delete existing dotfiles)' 
#** inputrc
rm -f $HOME/.inputrc 
ln -sfn  "$DotFilesDir"/.inputrc ~/.inputrc
# option -fn --> effect of overwrite
echo "    deleted and created symlink: ~/.inputrc --> "$DotFilesDir"/.inputrc" 
#** .emacs
rm -f $HOME/.emacs 
ln -sfn  "$DotFilesDir"/.emacs ~/.emacs
echo "    deleted and created symlink: ~/.emacs --> "$DotFilesDir"/.emacs" 

#** screenrc
rm -f $HOME/.screenrc 
ln -sfn  "$DotFilesDir"/.screenrc ~/.screenrc
# option -fn --> effect of overwrite
echo "    deleted and created symlink: ~/.screenrc --> "$DotFilesDir"/.screenrc" 


#** .termux (todo, but not now, cosmetic -> only install this on android phones)
rm -rf $HOME/.termux 
ln -sfn  "$DotFilesDir"/.termux ~/.termux
echo "    deleted and created symlink: ~/.termux --> "$DotFilesDir"/.termux" 

#** xterm-settings
