#!/bin/bash
# still todo
# for now: gsyn_up after every change / gsyn_down when switching device

set -u
set -e

echo "installing/updating DotFiles..."
DotFilesDir=~/DotFiles

#* add or replace in .bashrc source of mybashrc
grep_result=$(cat ~/.bashrc | grep ".mybashrc_all")

if [ -z "$grep_result" ]
then #empty
    echo "source "$DotFilesDir"/.mybashrc_all" >> ~/.bashrc
    # echo "empty --> append source-command"
    echo "    put source-command into the ~/.bashrc: source "$DotFilesDir"/.mybashrc_all" 
else
    # echo "not empty --> replace source-command"
    sed -i 's%^.*mybashrc_all.*$%source '$DotFilesDir'/\.mybashrc_all%g' ~/.bashrc
    echo "    put source-command into the ~/.bashrc: source "$DotFilesDir"/.mybashrc_all" 
    echo "    (was already there: $grep_result )"
    echo "    (replaced this line)"
fi


#* symlinks (delete existing dotfiles)
#** inputrc
rm -f $HOME/.inputrc 
ln -sfn  "$DotFilesDir"/.inputrc ~/.inputrc
# option -fn --> effect of overwrite
echo "    deleted and created symlink: ~/.inputrc --> "$DotFilesDir"/.inputrc" 
#** .emacs
rm -f $HOME/.emacs 
ln -sfn  "$DotFilesDir"/.emacs ~/.emacs
echo "    deleted and created symlink: ~/.emacs --> "$DotFilesDir"/.emacs" 


#** .termux
rm -rf $HOME/.termux 
ln -sfn  "$DotFilesDir"/.termux ~/.termux
echo "    deleted and created symlink: ~/.termux --> "$DotFilesDir"/.termux" 

#** xterm-settings
